//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assets_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub title: String,
    pub description: Option<String>,
    pub category: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::opportunities_opportunity_tags::Entity")]
    OpportunitiesOpportunityTags,
}

impl Related<super::opportunities_opportunity_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpportunitiesOpportunityTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
