//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assets_file")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub url: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub public_id: String,
    pub date_added: DateTimeWithTimeZone,
    pub folder: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::podcast_podcast::Entity")]
    PodcastPodcast,
}

impl Related<super::podcast_podcast::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PodcastPodcast.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
