//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "opportunities_opportunity_tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub opportunity_id: i64,
    pub tag_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets_tag::Entity",
        from = "Column::TagId",
        to = "super::assets_tag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AssetsTag,
    #[sea_orm(
        belongs_to = "super::opportunities_opportunity::Entity",
        from = "Column::OpportunityId",
        to = "super::opportunities_opportunity::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OpportunitiesOpportunity,
}

impl Related<super::assets_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetsTag.def()
    }
}

impl Related<super::opportunities_opportunity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpportunitiesOpportunity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
