//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "podcast_podcast")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub audio_id: Option<i64>,
    pub date_added: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
    pub listens: i32,
    pub cover_photo_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets_file::Entity",
        from = "Column::AudioId",
        to = "super::assets_file::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AssetsFile,
    #[sea_orm(
        belongs_to = "super::assets_image::Entity",
        from = "Column::CoverPhotoId",
        to = "super::assets_image::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AssetsImage,
    #[sea_orm(has_many = "super::podcast_host::Entity")]
    PodcastHost,
    #[sea_orm(has_many = "super::podcast_podcast_guests::Entity")]
    PodcastPodcastGuests,
}

impl Related<super::assets_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetsFile.def()
    }
}

impl Related<super::assets_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetsImage.def()
    }
}

impl Related<super::podcast_host::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PodcastHost.def()
    }
}

impl Related<super::podcast_podcast_guests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PodcastPodcastGuests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
