//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users_profile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub image_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub about: Option<String>,
    #[sea_orm(unique)]
    pub user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets_image::Entity",
        from = "Column::ImageId",
        to = "super::assets_image::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AssetsImage,
    #[sea_orm(
        belongs_to = "super::users_customuser::Entity",
        from = "Column::UserId",
        to = "super::users_customuser::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UsersCustomuser,
}

impl Related<super::assets_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetsImage.def()
    }
}

impl Related<super::users_customuser::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersCustomuser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
